# Generated by Django 4.2.4 on 2023-08-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('image', models.CharField(max_length=300, null=True)),
                ('yields', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookit.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField()),
                ('instruction', models.CharField(max_length=10000)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookit.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookit.recipe')),
            ],
        ),
    ]
