# Generated by Django 4.2.4 on 2023-08-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookit', '0002_alter_recipe_category_alter_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipeinstruction',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipenutrition',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
